DO NOT DELETE: SpawnJoin is developed and managed by Shades161
Config Version: '4.7'
Check for Updates: true
Announce Dev Join: true
Debug: false
LogCommandsToFile: false
Language: En
Use Economy: true
Join:
  Enabled: true
  AllowBypass: true
  Command: Hub
  Location:
    Hub: ExampleHub
    Lobby: ExampleLobby
    Warp: ExampleWarp
    Spawn: ExampleWorldName
Commands:
  Spawn:
    Enabled: true
    Delay: 1
  Hub:
    Enabled: true
    Delay: 1
  Lobby:
    Enabled: true
    Delay: 1
  Warp:
    Enabled: true
    Delay: 1
  Tpr:
    Enabled: true
    Delay: 1
    Cooldown: 3600
  Spectate:
    Enabled: true
    Delay: 1
  Home:
    Enabled: true
    Delay: 1
    DefaultLimit: 1
    UseRankLimits: false
    GlobalLimit:
      Enabled: false
      Limit: 3
  Sign:
    Enabled: true
Inventory:
  Use: true
  ListCommandOverride: true
TPR:
  Max: 1000
  Worlds:
  - world
  - ExampleWorld1
Spawn:
  Save to File: true
  PerWorld: true
Respawn:
  Use: true
  PerWorld: true
  Default:
    World: world
Signs:
  Log: false
  UseBreakPermission: true
NOTIFICATIONS:
  Spawn: true
  Hub: true
  Lobby: true
  Warp: true
  Spectate: true
  Home: true
  Respawn: true
  Tpr: true
  TprAllowed: true
  Bypass: true
  Perm: true
  Args: true
  SpawnJoin: true
  Update: true